# Maintained by "drom project"
.PHONY: $(DROMNS)build $(DROMNS)build-deps $(DROMNS)fmt $(DROMNS)fmt-check
.PHONY: $(DROMNS)install $(DROMNS)dev-deps $(DROMNS)test
.PHONY: $(DROMNS)clean $(DROMNS)distclean

DROM_DEV_DEPS := merlin ocamlformat odoc $(DEV_DEPS)


SPHINX_TARGET:=_drom/docs/sphinx

ODOC_TARGET:=_drom/docs/doc/.


$(DROMNS)build:
	./scripts/before.sh build
	opam exec -- dune build @install
	./scripts/copy-bin.sh autofonce autofonce_core autofonce_lib autofonce_m4 autofonce_share autofonce_patch autofonce_config autofonce_misc ez_win32 ez_call
	./scripts/after.sh build

$(DROMNS)build-deps:
	if ! [ -e _opam ]; then \
	   opam switch create . 4.14.2 --no-install; \
	fi
	opam install ./opam/*.opam ./vendors/ANSITerminal/*.opam --deps-only


.PHONY: $(DROMNS)doc-common $(DROMNS)odoc $(DROMNS)view
.PHONY: $(DROMNS)sphinx
$(DROMNS)doc-common: $(DROMNS)build
	mkdir -p _drom/docs
	rsync -auv docs/. _drom/docs/.

$(DROMNS)sphinx: $(DROMNS)doc-common
	./scripts/before.sh sphinx ${SPHINX_TARGET}
	sphinx-build sphinx ${SPHINX_TARGET}
	./scripts/after.sh sphinx  ${SPHINX_TARGET}

$(DROMNS)odoc: $(DROMNS)doc-common
	mkdir -p ${ODOC_TARGET}
	./scripts/before.sh odoc ${ODOC_TARGET}
	opam exec -- dune build @doc
	rsync -auv --delete _build/default/_doc/_html/. ${ODOC_TARGET}
	./scripts/after.sh odoc ${ODOC_TARGET}

$(DROMNS)doc: $(DROMNS)doc-common $(DROMNS)odoc $(DROMNS)sphinx

$(DROMNS)view:
	xdg-open file://$$(pwd)/_drom/docs/index.html

$(DROMNS)fmt:
	opam exec -- dune build @fmt --auto-promote

$(DROMNS)fmt-check:
	opam exec -- dune build @fmt

$(DROMNS)install:
	opam pin -y --no-action -k path .
	opam install -y .

$(DROMNS)opam:
	opam pin -k path .

$(DROMNS)uninstall:
	opam uninstall .

$(DROMNS)dev-deps:
	opam install ./opam/*.opam --deps-only --with-doc --with-test

$(DROMNS)test:
	./scripts/before.sh test
	opam exec -- dune build @runtest
	./scripts/after.sh test

$(DROMNS)clean:
	rm -rf _build
	rm -f *.exe *~
	./scripts/after.sh clean

$(DROMNS)distclean: $(DROMNS)clean
	rm -rf _opam _drom
	./scripts/after.sh distclean


